(function(){
    const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    window.getProfileHTML=function(){
        const p=AppState.profile||{username:AppState.currentUser||'DemoLion',email:'demo@rawr.casino',bio:'King of the jungle!',kyc:'Not submitted'}; AppState.profile=p;
        const tab=AppState.profileTab||'overview';
        const overview=`<div class="profile-overview-grid"><article class="profile-panel"><h2><i class="fas fa-chart-line"></i> Account Overview</h2><dl><div><dt>Total RAWR Mined</dt><dd>${Number(AppState.totalMined).toFixed(2)}</dd></div><div><dt>Games Played</dt><dd>${(AppState.gameHistory||[]).length}</dd></div><div><dt>Login Streak</dt><dd>${AppState.loginStreak} days</dd></div><div><dt>Wallet Status</dt><dd>${AppState.walletConnected?'Connected (Demo)':'Not connected'}</dd></div></dl></article><article class="profile-panel"><h2><i class="fas fa-id-card"></i> Personal Information</h2><dl><div><dt>Full Name</dt><dd>Demo Lion</dd></div><div><dt>Email Address</dt><dd>${esc(p.email)}</dd></div><div><dt>Country</dt><dd>Demo account</dd></div><div><dt>KYC Status</dt><dd><span class="profile-status">${esc(p.kyc)}</span></dd></div></dl><button class="btn btn-secondary" onclick="switchProfileTab('kyc')">Review KYC status</button></article></div>`;
        const settings=`<div class="profile-panel"><h2><i class="fas fa-user-cog"></i> Profile Settings</h2><form onsubmit="saveDemoProfile(event)"><div class="profile-form-grid"><label>Username<input name="username" value="${esc(p.username)}" required></label><label>Email Address<input name="email" type="email" value="${esc(p.email)}" required></label><label class="wide">Bio<textarea name="bio" rows="3">${esc(p.bio)}</textarea></label></div><button class="btn btn-primary">Save Changes</button></form><h3>Change Password</h3><form onsubmit="simulatePasswordChange(event)" class="profile-form-grid"><label>Current Password<input type="password" required></label><label>New Password<input type="password" minlength="6" required></label><label>Confirm New Password<input type="password" minlength="6" required></label><button class="btn btn-secondary">Update Password</button></form><p class="demo-disclaimer">Password changes are simulated and are not stored.</p></div>`;
        const kyc=`<div class="profile-panel"><h2><i class="fas fa-shield-alt"></i> KYC Verification</h2><p>Verification status: <span class="profile-status">${esc(p.kyc)}</span></p><p>Complete verification in the live application. This portfolio demo never uploads or stores identity documents.</p><form onsubmit="submitDemoKyc(event)" class="profile-form-grid"><label>Full Name<input name="fullName" autocomplete="off" required></label><label>Date of Birth<input name="dob" type="date" required></label><label>Country<input name="country" required></label><label>Contact Number<input name="phone" type="tel"></label><label>ID Type<select name="idType"><option>Passport</option><option>National ID</option><option>Driver License</option></select></label><label>ID Number<input name="idNumber" autocomplete="off" required></label><label class="wide">Front of ID document<input type="file" accept="image/jpeg,image/png" disabled><small>Uploads disabled in portfolio demo.</small></label><label class="wide">Selfie verification<input type="file" accept="image/jpeg,image/png" disabled><small>Uploads disabled in portfolio demo.</small></label><label class="wide check"><input type="checkbox" required> I confirm the sample information provided for this demonstration.</label><button class="btn btn-primary">Submit for Verification</button></form></div>`;
        return `<section class="profile-page"><header class="profile-hero"><div class="profile-avatar">🦁</div><div><h1>${esc(p.username)}</h1><p>${esc(p.email)}</p><span class="profile-status">${esc(p.kyc)} Account</span></div></header><nav class="profile-tabs" aria-label="Profile sections">${[['overview','Overview'],['settings','Settings'],['kyc','KYC Verification']].map(([id,label])=>`<button class="${tab===id?'active':''}" onclick="switchProfileTab('${id}')">${label}</button>`).join('')}</nav>${tab==='overview'?overview:tab==='settings'?settings:kyc}</section>`;
    };
    window.switchProfileTab=function(tab){AppState.profileTab=tab;loadDashboardContent('profile');};
    window.saveDemoProfile=function(event){event.preventDefault();const f=new FormData(event.currentTarget);AppState.profile=AppState.profile||{};Object.assign(AppState.profile,{username:f.get('username').trim(),email:f.get('email').trim(),bio:f.get('bio')});AppState.currentUser=AppState.profile.username;saveState();updateBalances();showNotification('Profile updated successfully!','success');loadDashboardContent('profile');};
    window.simulatePasswordChange=function(event){event.preventDefault();const inputs=[...event.currentTarget.querySelectorAll('input')];if(inputs[1].value!==inputs[2].value)return showNotification('New passwords do not match.','error');showNotification('Password changed (demo only).','success');event.currentTarget.reset();};
    window.submitDemoKyc=function(event){event.preventDefault();AppState.profile=AppState.profile||{};AppState.profile.kyc='Pending';saveState();showNotification('Verification request submitted in demo mode. No documents were uploaded.','success');loadDashboardContent('profile');};
})();
