/* Local admin console using fictional demo fixtures from demo-data/data.js. */
(function () {
    const data = window.RAWR_DEMO_DATA;
    try { const saved = JSON.parse(localStorage.getItem('rawr_demo_admin_data') || 'null'); if (saved) { data.users = saved.users || data.users; data.kycRequests = saved.kycRequests || data.kycRequests; } } catch (_) { /* Ignore invalid local demo data. */ }
    const persistAdminData = () => localStorage.setItem('rawr_demo_admin_data', JSON.stringify({ users: data.users, kycRequests: data.kycRequests }));
    const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const nav = (active) => `<nav class="admin-demo-nav"><strong>RAWR ADMIN</strong><button class="${active==='dashboard'?'active':''}" onclick="renderAdminPage('dashboard')">Overview</button><button class="${active==='users'?'active':''}" onclick="renderAdminPage('users')">Manage Users</button><button class="${active==='kyc'?'active':''}" onclick="renderAdminPage('kyc')">KYC Requests</button><button onclick="showDashboardTab('dashboard')">← Player Site</button></nav>`;
    const shell = (active, content) => `<div class="admin-demo">${nav(active)}<main class="admin-demo-main"><div class="demo-admin-note"><i class="fas fa-info-circle"></i> Admin preview · sample data and actions stay in this browser.</div>${content}</main></div>`;
    const heading = (title, desc, action='') => `<header class="admin-page-heading"><div><h1>${title}</h1><p>${desc}</p></div>${action}</header>`;
    const table = (rows) => `<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>User</th><th>Email</th><th>Balance</th><th>Status</th><th>KYC</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table></div>`;
    const userRows = (items) => items.map(u=>`<tr><td><strong>${esc(u.username)}</strong><small>#${Number(u.id)}</small></td><td>${esc(u.email)}</td><td>${Number(u.balance).toFixed(2)} RAWR</td><td><span class="admin-status ${esc(u.status.toLowerCase())}">${esc(u.status)}</span></td><td><span class="admin-status ${esc(u.kyc.toLowerCase().replaceAll(' ','-'))}">${esc(u.kyc)}</span></td><td><button class="admin-action" onclick="renderAdminPage('edit',${Number(u.id)})">Manage</button></td></tr>`).join('');
    window.renderAdminPage = function(page='dashboard', userId){
        AppState.adminPage=page; AppState.adminUserId=userId||AppState.adminUserId;
        const route = page === 'dashboard' ? '#/admin' : page === 'edit' ? `#/admin/edit-user/${AppState.adminUserId || ''}` : `#/admin/${page}`;
        if (location.hash !== route) location.hash = route;
        let content='';
        if(page==='dashboard') content=heading('Admin Dashboard','Manage users, KYC requests, and system activity')+`<div class="admin-stat-grid">${[['Users',data.stats.totalUsers,'fa-users'],['Active Users',data.stats.activeUsers,'fa-user-check'],['Pending KYC',data.stats.pendingKyc,'fa-id-card'],['Games Played',data.stats.gamesPlayed.toLocaleString(),'fa-dice']].map(([n,v,i])=>`<article class="admin-stat"><i class="fas ${i}"></i><strong>${v}</strong><span>${n}</span></article>`).join('')}</div><section class="admin-panel"><div class="admin-panel-title"><h2>Recent Users</h2><button class="admin-action" onclick="renderAdminPage('users')">View all users</button></div>${table(userRows(data.users.slice(0,5)))}</section><section class="admin-panel"><div class="admin-panel-title"><h2>Recent KYC Requests</h2><button class="admin-action" onclick="renderAdminPage('kyc')">Review requests</button></div>${data.kycRequests.filter(k=>k.status==='Pending').map(k=>`<div class="admin-kyc-row"><span><strong>${k.username}</strong><small>${k.type} · ${k.submitted}</small></span><span class="admin-status pending">${k.status}</span><button class="admin-action" onclick="renderAdminPage('kyc')">Review</button></div>`).join('')}</section>`;
        if(page==='users') content=heading('Manage Users','Search and review demo player accounts')+`<section class="admin-panel"><label class="admin-search-label" for="user-search">Search users</label><input id="user-search" class="admin-search" placeholder="Search by username or email" oninput="filterDemoUsers(this.value)"><div id="admin-user-table">${table(userRows(data.users))}</div></section>`;
        if(page==='edit') { const u=data.users.find(x=>x.id===Number(userId||AppState.adminUserId))||data.users[0]; content=heading('Edit User',`Manage demo account #${Number(u.id)}`,'<button class="admin-action" onclick="renderAdminPage(\'users\')">← Back to users</button>')+`<form class="admin-panel admin-edit-form" onsubmit="saveDemoUser(event,${Number(u.id)})"><div class="admin-form-grid"><label>Username<input name="username" value="${esc(u.username)}" required></label><label>Email Address<input type="email" name="email" value="${esc(u.email)}" required></label><label>RAWR Balance<input type="number" step="0.01" name="balance" value="${Number(u.balance)}" required></label><label>Tickets<input type="number" name="tickets" value="${Number(u.tickets)}" required></label><label>Account Status<select name="status">${['Active','Suspended'].map(s=>`<option ${s===u.status?'selected':''}>${s}</option>`).join('')}</select></label><label>KYC Status<select name="kyc">${['Not submitted','Pending','Approved','Rejected'].map(s=>`<option ${s===u.kyc?'selected':''}>${s}</option>`).join('')}</select></label></div><button class="btn btn-primary" type="submit">Save Changes</button></form>`; }
        if(page==='kyc') { const state=AppState.kycFilter||'Pending'; const items=data.kycRequests.filter(k=>state==='All'||k.status===state); content=heading('KYC Requests','Review fictional verification requests')+`<section class="admin-panel"><div class="admin-tabs">${['Pending','Approved','Rejected','All'].map(s=>`<button class="${s===state?'active':''}" onclick="setKycFilter('${s}')">${s}</button>`).join('')}</div>${items.length?items.map(k=>`<article class="admin-kyc-card"><div><strong>${esc(k.username)}</strong><small>${esc(k.id)} · ${esc(k.type)} · Submitted ${esc(k.submitted)}</small></div><span class="admin-status ${esc(k.status.toLowerCase())}">${esc(k.status)}</span><div class="admin-kyc-actions">${k.status==='Pending'?`<button class="admin-action approve" onclick="updateKyc('${esc(k.id)}','Approved')">Approve</button><button class="admin-action reject" onclick="updateKyc('${esc(k.id)}','Rejected')">Reject</button>`:`<button class="admin-action" onclick="showNotification('This is fictional demo KYC data. No documents are available.','info')">Details</button>`}</div></article>`).join(''):'<p class="admin-empty">No requests in this category.</p>'}<p class="admin-private-note"><i class="fas fa-lock"></i> No identity documents are included in this public demo.</p></section>`; }
        const host=document.getElementById('dashboard-content'); if(host) host.innerHTML=shell(page==='edit'?'users':page,content); saveState();
    };
    window.getAdminHTML=function(){ return `<div id="admin-console-mount"></div>`; };
    const oldInit=window.initializeTabFunctionality; window.initializeTabFunctionality=function(tab){if(oldInit)oldInit(tab);if(tab==='admin')renderAdminPage(AppState.adminPage||'dashboard');};
    window.filterDemoUsers=function(query){const q=query.trim().toLowerCase();const items=data.users.filter(u=>`${u.username} ${u.email} ${u.status} ${u.kyc}`.toLowerCase().includes(q));const host=document.getElementById('admin-user-table');if(host)host.innerHTML=items.length?table(userRows(items)):'<p class="admin-empty">No users match that search.</p>';};
    window.saveDemoUser=function(event,id){event.preventDefault();const u=data.users.find(x=>x.id===id);const form=new FormData(event.currentTarget);Object.assign(u,{username:form.get('username'),email:form.get('email'),balance:Number(form.get('balance')),tickets:Number(form.get('tickets')),status:form.get('status'),kyc:form.get('kyc')});persistAdminData();showNotification('Demo user updated.','success');renderAdminPage('edit',id);};
    window.setKycFilter=function(filter){AppState.kycFilter=filter;renderAdminPage('kyc');};
    window.updateKyc=function(id,status){const req=data.kycRequests.find(k=>k.id===id);if(!req)return;req.status=status;const u=data.users.find(x=>x.username===req.username);if(u)u.kyc=status;persistAdminData();showNotification(`KYC request ${status.toLowerCase()} (demo).`,'success');renderAdminPage('kyc');};
})();
